web:
  build: .
  links:
   - db
   - worker
  ports:
   - "8000:8000"
  env_file:
   - server/.env
  volumes:
   - server:/code/server
  working_dir: /code/server/
  command: python app.py
worker:
  build: .
  working_dir: /code/server/
  command: celery --loglevel=DEBUG --concurrency=1 -A app.celery worker
  volumes:
   - server:/code/server
  env_file:
   - server/.env
  environment:
   C_FORCE_ROOT: true
  links:
   - db
db:
  image: redis
