web:
  extends:
    file: common.yml
    service: web
  links:
   - db
   - worker
  command: gunicorn -b 0.0.0.0:8000 -w 4 app:app
  restart: always
  environment:
    SERVER_NAME: services.birc.au.dk
worker:
  extends:
    file: common.yml
    service: worker
  links:
   - db
  command: celery --loglevel=INFO --concurrency=1 -A app.celery worker
  restart: always
  environment:
    SERVER_NAME: services.birc.au.dk
db:
  extends:
    file: common.yml
    service: db
  restart: always
